UCSCSecurityBundle:
    resource: "@UCSCSecurityBundle/Resources/config/routing.yml"
    prefix:   /

UCSCRegistrationBundle:
    resource: "@UCSCRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

UCSCDatabaseBundle:
    resource: "@UCSCDatabaseBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
