login:
    pattern:   /login
    defaults:  { _controller: UCSCSecurityBundle:Security:login }

login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
    
register_check:
    pattern:   /register
    defaults:  { _controller: UCSCSecurityBundle:Security:register }
    requirements:
        _method:  POST
        
register_form:
    pattern:   /register
    defaults:  { _controller: UCSCSecurityBundle:Security:registerform }
