parameters:
#    ucsc_result.example.class: UCSC\ResultBundle\Example

services:
#    ucsc_result.example:
#        class: %ucsc_result.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
