student_reg:
    pattern:  /student/register
    defaults: { _controller: UCSCRegistrationBundle:Default:studentreg }
    requirements:
        _method:  POST

student_form:
    pattern:  /student/register
    defaults: { _controller: UCSCRegistrationBundle:Default:studentform }
